<!doctype html>
<html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="Taşıtınıza ve ihtiyacınıza uygun servisi bulun, kolayca randevu talep edin."><title>Servis bul · Sanayi Randevu</title><link rel="stylesheet" href="{{ asset('css/booking-directory.css') }}"><script defer src="{{ asset('js/booking-directory.js') }}"></script></head>
<body><header class="directory-header"><a class="directory-brand" href="{{ route('directory.index') }}"><span class="brand-symbol" aria-hidden="true">↗</span>sanayi<span>randevu</span></a><a class="owner-link" href="{{ route('login') }}">İşletme girişi <span aria-hidden="true">↗</span></a></header>
<main class="directory-main">
@php($step = !$region ? 1 : (!$vehicle ? 2 : (!$service ? 3 : 4)))
<nav class="steps" aria-label="Randevu adımları">@foreach (['Konum','Taşıt','Hizmet','Servis'] as $label)<span @if($loop->iteration === $step) aria-current="step" @endif class="{{ $loop->iteration <= $step ? 'reached' : '' }}"><b>{{ $loop->iteration }}</b>{{ $label }}</span>@endforeach</nav>
@if($region)
<div class="selection-bar"><a href="{{ route('directory.index') }}">⌖ {{ $regions[$region] }} <u>Değiştir</u></a>@if($vehicle)<a href="{{ route('directory.index', ['region'=>$region]) }}">{{ $vehicles[$vehicle] }} <u>Değiştir</u></a>@endif @if($service)<a href="{{ route('directory.index', ['region'=>$region,'vehicle'=>$vehicle]) }}">{{ $service->name }} <u>Değiştir</u></a>@endif</div>
@endif
@if(!$region)
<section class="intro"><p class="eyebrow">YOLUNUZ DOĞRU SERVİSE ÇIKSIN</p><h1>Aracınıza uygun servis.<br><em>Size uygun zaman.</em></h1><p>Bulunduğunuz yeri seçin, ihtiyacınıza uygun işletmelerle buluşun.</p></section>
<section class="location-panel"><div><h2>Nerede servis arıyorsunuz?</h2><p>Konumunuzla başlayın veya aşağıdan il seçin.</p></div><button id="locate" class="primary" type="button">⌖ Konumumu kullan</button><p class="privacy">Konum izni verirseniz ilinizi bulmak için koordinatlarınız BigDataCloud’a iletilir. Uygulamamız koordinatlarınızı kaydetmez. <a href="https://www.bigdatacloud.com/privacy-policy" target="_blank" rel="noopener noreferrer">Gizlilik bilgisi</a></p><p id="geo-status" role="status" aria-live="polite"></p></section>
<section id="istanbul-sides" class="side-panel" hidden><h2>İstanbul’da hangi yaka?</h2><div class="city-grid">@foreach(['34-avrupa','34-anadolu'] as $key)<a class="city" href="{{ route('directory.index', ['region'=>$key]) }}">{{ $regions[$key] }} <span>→</span></a>@endforeach</div></section>
<section aria-labelledby="city-title"><div class="section-heading"><h2 id="city-title">İl seçin</h2><span>İstanbul için yakanızı seçin</span></div><label class="sr-only" for="city-search">İl ara</label><input class="search" id="city-search" type="search" placeholder="İl adı yazın…" autocomplete="off"><p id="city-empty" hidden role="status">Bu isimde il bulunamadı. Aramanızı değiştirin.</p><div class="city-grid" id="city-grid">@foreach($regions as $key=>$label)<a class="city" data-city="{{ $label }}" data-code="{{ $key }}" href="{{ route('directory.index', ['region'=>$key]) }}">{{ $label }}<span aria-hidden="true">↗</span></a>@endforeach</div></section>
@elseif(!$vehicle)
<section class="intro"><p class="eyebrow">02 / TAŞITINIZ</p><h1>Ne kullanıyorsunuz?</h1><p>Taşıtınızı seçin, size uygun hizmetlere geçelim.</p></section>
<div class="choice-grid">@foreach($vehicles as $key=>$label)<a class="choice vehicle-card" href="{{ route('directory.index', ['region'=>$region,'vehicle'=>$key]) }}"><span class="vehicle-art" aria-hidden="true"><svg viewBox="0 0 160 90" fill="none" stroke="currentColor" stroke-width="4" stroke-linecap="round" stroke-linejoin="round">@if($key==='motosiklet')<circle cx="37" cy="64" r="19"/><circle cx="124" cy="64" r="19"/><path d="M37 64 65 35h34l25 29M68 35l13 29H37m44 0 25-43h14M57 30h20M90 21h16"/>@elseif($key==='agir-vasita')<path d="M12 18h85v49H12zM97 35h29l22 20v12H97M109 35v20h39"/><circle cx="39" cy="69" r="12" fill="#eef5f3"/><circle cx="123" cy="69" r="12" fill="#eef5f3"/>@else<path d="m18 47 20-26h60l24 26 20 8v16H13V53zM38 21l-7 26h91M73 23v24"/><circle cx="39" cy="69" r="12" fill="#eef5f3"/><circle cx="116" cy="69" r="12" fill="#eef5f3"/>@endif</svg></span><span class="choice-title">{{ $label }} <b>↗</b></span><span class="muted">Hizmetleri keşfet</span></a>@endforeach</div>
@elseif(!$service)
<section class="intro"><p class="eyebrow">03 / İHTİYACINIZ</p><h1>Nasıl yardımcı olabilirler?</h1><p>{{ $vehicles[$vehicle] }} için aradığınız hizmeti seçin.</p></section>
<div class="choice-grid services">@forelse($services as $option)<a class="choice" href="{{ route('directory.index', ['region'=>$region,'vehicle'=>$vehicle,'service'=>$option->id]) }}"><span class="service-mark" aria-hidden="true">{{ sprintf('%02d', $loop->iteration) }}</span><span class="choice-title">{{ $option->name }} <b>→</b></span><span class="muted">Bu hizmeti veren servisleri gör</span></a>@empty<div class="empty-state"><h2>Hizmetler hazırlanıyor.</h2><p>Bu taşıt için henüz hizmet eklenmemiş. Başka bir taşıt seçebilirsiniz.</p><a class="primary" href="{{ route('directory.index', ['region'=>$region]) }}">Taşıt seçimine dön</a></div>@endforelse</div>
@else
<section class="intro"><p class="eyebrow">04 / SERVİSİNİZ</p><h1>Doğru yer, bir adım ötede.</h1><p>{{ $regions[$region] }} · {{ $service->name }} için {{ $shops->total() }} işletme</p></section>
<div class="shops">@forelse($shops as $shop)<article class="shop-card"><div class="shop-icon" aria-hidden="true">↗</div><div class="shop-details"><span class="shop-region">{{ $regions[$region] }}</span><h2>{{ $shop->display_name }}</h2>@if($shop->public_address)<p>{{ $shop->public_address }}</p>@endif<div class="tags"><span>{{ $vehicles[$vehicle] }}</span><span>{{ $service->name }}</span></div></div><a class="primary" href="{{ route('booking.show', ['publicId'=>$shop->public_id,'vehicle'=>$vehicle,'service'=>$service->id]) }}">Randevu al <span aria-hidden="true">→</span></a></article>@empty<section class="empty-state"><span class="empty-icon" aria-hidden="true">⌖</span><h2>Bu seçim için henüz işletme yok.</h2><p>Başka bir hizmet veya il seçerek aramaya devam edebilirsiniz.</p><a class="primary" href="{{ route('directory.index', ['region'=>$region,'vehicle'=>$vehicle]) }}">Hizmeti değiştir</a><a class="text-link" href="{{ route('directory.index') }}">Başka il seç</a></section>@endforelse</div>
@if($shops->hasPages())<nav class="pagination" aria-label="İşletme sayfaları">@if($shops->previousPageUrl())<a class="city" href="{{ $shops->previousPageUrl() }}">← Önceki</a>@endif<span>{{ $shops->currentPage() }} / {{ $shops->lastPage() }}</span>@if($shops->nextPageUrl())<a class="city" href="{{ $shops->nextPageUrl() }}">Sonraki →</a>@endif</nav>@endif
<p class="muted">İşletmeler ada göre sıralanır. Uygun gün ve saatleri işletmenin sayfasında görebilirsiniz.</p>
@endif
<footer class="directory-footer"><span>Servisi bul. Zamanını seç. Yoluna devam et.</span><span>Üyelik gerekmez · Randevular işletme onayına tabidir.</span></footer>
</main></body></html>
