@extends('layouts.app')
@section('page-title','İşletme detayı')
@section('content')
<div class="d-flex flex-wrap align-items-center justify-content-between gap-3 mb-4"><div><h3 class="mb-1">{{ ($business['name'] ?? '') ?: $owner->name }}</h3><p class="text-muted mb-0">{{ $owner->name }} · {{ $owner->email }}</p></div><a class="btn btn-outline-secondary" href="{{ route('users.index') }}">İşletmelere dön</a></div>
<div class="row g-3 mb-4">@foreach($counts as $label=>$count)<div class="col-6 col-md-4 col-xl"><div class="card h-100 mb-0"><div class="card-body"><span class="text-muted">{{ $label }}</span><h3 class="mt-2 mb-0">{{ number_format($count,0,',','.') }}</h3></div></div></div>@endforeach</div>
<div class="card"><div class="card-body"><h5>Bu ayın kullanım özeti</h5><p>{{ $usage->month_services }} servis · {{ $usage->month_invoices }} fatura · {{ $usage->month_appointments }} randevu · {{ $usage->month_verification_sms }} doğrulama SMS denemesi · {{ $usage->month_appointment_sms }} randevu onay / {{ $usage->month_vehicle_sms }} araç SMS’i sağlayıcı tarafından kabul edildi</p><a href="{{ route('business-usage.index') }}" class="btn btn-outline-secondary">Tüm işletmelerin kullanımını gör</a></div></div>
<div class="card"><div class="card-body"><h5>İşletmeye panel bildirimi gönder</h5><form method="post" action="{{ route('announcements.store') }}">@csrf<input type="hidden" name="audience" value="selected"><input type="hidden" name="owner_ids[]" value="{{ $owner->id }}"><label class="form-label">Başlık</label><input class="form-control mb-2" name="title" required maxlength="150"><label class="form-label">Mesaj</label><textarea class="form-control mb-3" name="body" rows="3" required maxlength="5000"></textarea><button class="btn btn-secondary">Bildirim gönder</button></form></div></div>
<div class="row g-3">
<div class="col-lg-6"><div class="card h-100 mb-0"><div class="card-body"><h5>Paket ve kapasite</h5>
<p><strong>{{ $capacity['plan']?->title ?? 'Paket atanmamış' }}</strong> <span class="badge {{ $owner->subscription_suspended_at ? 'bg-danger' : 'bg-light text-dark' }}">{{ $owner->subscription_suspended_at ? 'Askıya alınmış' : ($owner->subscription_expire_date && \Carbon\Carbon::parse($owner->subscription_expire_date)->lt(today()) ? 'Süresi dolmuş' : 'Askıda değil') }}</span></p>
<dl class="row"><dt class="col-6">Bitiş tarihi</dt><dd class="col-6">{{ $owner->subscription_expire_date ? dateFormat($owner->subscription_expire_date) : 'Süresiz' }}</dd><dt class="col-6">Araç kapasitesi</dt><dd class="col-6">{{ $capacity['used'] }} / {{ $capacity['limit'] ?? 'Sınırsız' }}</dd><dt class="col-6">Ek kapasite</dt><dd class="col-6">{{ $capacity['extra'] }} araç</dd><dt class="col-6">Kalan kapasite</dt><dd class="col-6">{{ $capacity['remaining'] ?? 'Sınırsız' }}</dd></dl>
@if($owner->subscription_suspended_at)<p class="text-danger">{{ $owner->subscription_suspension_reason }}</p>@endif
<a href="#" class="btn btn-outline-secondary customModal" data-size="lg" data-title="Aboneliği düzenle" data-url="{{ route('subscription-admin.edit',$owner->id) }}">Aboneliği düzenle</a>
</div></div></div>
<div class="col-lg-6"><div class="card h-100 mb-0"><div class="card-body"><h5>İşletme ve hesap bilgileri</h5><dl class="row">@foreach(['phone'=>'Telefon','address'=>'Adres','city'=>'İl','email'=>'İşletme e-postası','tax_office'=>'Vergi dairesi','tax_number'=>'TCKN / VKN'] as $field=>$label)<dt class="col-sm-5">{{ $label }}</dt><dd class="col-sm-7 text-break">{{ ($business[$field] ?? '') ?: 'Doldurulmamış' }}</dd>@endforeach<dt class="col-sm-5">İki aşamalı doğrulama</dt><dd class="col-sm-7">{{ $owner->twofa_secret ? 'Etkin' : ($owner->twofa_required ? 'Kurulum bekleniyor' : 'Devre dışı') }}</dd></dl>
<a class="btn btn-outline-secondary" href="{{ route('two-factor-admin.index') }}">Hesap güvenliği</a>
</div></div></div>
<div class="col-lg-6"><div class="card h-100 mb-0"><div class="card-body"><h5>Randevu sistemi</h5><p>Randevu alımı: <strong>{{ $profile?->is_active ? 'Açık' : 'Kapalı / yapılandırılmamış' }}</strong></p><p>Onay bekleyen randevu: <strong>{{ $pendingAppointments }}</strong></p>
@if($profile)<p class="small text-break">{{ $profile->publicUrl() }}</p><a class="btn btn-outline-secondary mb-3" href="{{ $profile->publicUrl() }}" target="_blank" rel="noopener noreferrer">Randevu sayfasını aç</a><ul class="list-unstyled small">@foreach(\App\Models\AppointmentProfile::days() as $day=>$label)<li class="mb-1"><strong>{{ $label }}:</strong> {{ collect($profile->weekly_hours[$day] ?? [])->sort()->map(fn($hour)=>sprintf('%02d:00',$hour))->implode(', ') ?: 'Kapalı' }}</li>@endforeach</ul>@endif
</div></div></div>
<div class="col-lg-6"><div class="card h-100 mb-0"><div class="card-body"><h5>Kurulum ve eksik ayarlar</h5>@forelse($warnings as $warning)<div class="border-bottom py-2"><strong>{{ $warning['title'] }}</strong><p class="small text-muted mb-0">{{ $warning['description'] }}</p></div>@empty<p class="text-success">Kontrol edilen ayarlarda eksik bulunamadı.</p>@endforelse</div></div></div>
<div class="col-12"><div class="card"><div class="card-body"><h5>Destek biletleri <span class="badge bg-light text-dark">{{ $ticketCount }} açık bilet</span></h5><div class="table-responsive"><table class="table"><thead><tr><th>Konu</th><th>Durum</th><th>Son mesaj</th><th></th></tr></thead><tbody>@forelse($tickets as $ticket)<tr><td class="text-break">{{ $ticket->subject }}</td><td>{{ \App\Models\SupportTicket::STATUSES[$ticket->status] ?? $ticket->status }}</td><td>{{ $ticket->last_message_at ? dateFormat($ticket->last_message_at).' '.timeFormat($ticket->last_message_at) : '—' }}</td><td><a class="btn btn-sm btn-outline-secondary" href="{{ route('support.show',$ticket->id) }}">Bileti aç</a></td></tr>@empty<tr><td colspan="4">Destek bileti bulunmuyor.</td></tr>@endforelse</tbody></table></div></div></div></div>
</div>
@endsection
