<?php

return [
    'groups' => [
        'baslangic' => ['title' => 'İlk kurulum', 'description' => 'İşletmenizin kimliği, logosu ve temel ayarları.'],
        'musteri' => ['title' => 'Müşteri ve araç', 'description' => 'Kayıtlar, QR bağlantıları ve hazır araç listeleri.'],
        'randevu' => ['title' => 'Randevu yönetimi', 'description' => 'Çalışma saatleri, talepler ve genel servis araması.'],
        'servis' => ['title' => 'Servis ve ekip', 'description' => 'İşçilik, çalışanlar ve günlük servis takibi.'],
        'fatura' => ['title' => 'Fatura ve tahsilat', 'description' => 'Fatura içeriği, indirimler, ödemeler ve paylaşım.'],
        'stok' => ['title' => 'Ürünler ve finans', 'description' => 'Stok hareketleri, elden satış ve işletme hesapları.'],
        'hesap' => ['title' => 'Hesap ve destek', 'description' => 'Güvenlik, abonelik ve destek biletleri.'],
    ],
    'topics' => [
        [
            'id' => 'is-akisi', 'group' => 'baslangic', 'title' => 'Bir işin baştan sona yolculuğu',
            'intro' => 'Randevu, servis ve fatura birbirini tamamlayan ayrı kayıtlardır. Randevu müşterinin geleceği zamanı, servis yapılan işi, fatura ise ücretleri ve tahsilatı takip eder.',
            'steps' => ['Önce işletme bilgileriniz ve logonuzla panelinizi hazırlayın. Marka/model, vergi, birim ve servis türlerini kontrol edin.', 'Müşteriyi ve aracını kaydedin. Müşteri zaten kayıtlıysa yeni müşteri açmak yerine mevcut kaydı kullanın.', 'Müşteri randevu aldıysa talebini inceleyin. Servis kaydını ayrıca açın; randevu onayı tek başına servis veya tahsilat değildir.', 'Yapılacak işleri servis kaydına ekleyin. Fatura içeriğini kontrol edin; kullanılan ürünleri ve varsa indirimi girin.', 'Alınan ödemeyi faturaya kaydedin. Servis durumunu işin gerçek ilerleyişine göre güncelleyin.'],
            'notes' => ['Servisin tamamlanması ile faturanın ödenmesi farklı işlemlerdir. İkisini de ayrı takip edin.', 'Sağ üstteki zil güncel talepleri ve destek yanıtlarını, uyarı simgesi tamamlanmamış kurulum adımlarını gösterir.'],
        ],
        [
            'id' => 'isletme-bilgileri', 'group' => 'baslangic', 'title' => 'Faturalarda görünen işletme bilgileri',
            'intro' => 'Faturanın satıcı bölümündeki bilgiler esnaf hesabınızın “İşletme bilgileri” alanından alınır. Bu alan, müşteri bilgileriyle karıştırılmamalıdır.',
            'steps' => ['Ayarlar → İşletme bilgileri bölümünü açın.', 'İşletme/ticaret unvanı, adres, telefon ve e-postanızı girin. Kullanacağınız vergi dairesi ve TCKN/VKN bilgilerini ekleyin.', 'İl, ilçe, posta kodu, web sitesi, MERSİS ve ticaret sicili gibi ek alanları ihtiyacınıza göre tamamlayın.', 'Kaydedin ve yeni oluşturduğunuz faturanın satıcı bölümünü kontrol edin.'],
            'notes' => ['Alanlar isteğe bağlıdır. Doldurmadığınız bilgiler faturada boş kalabilir.', 'Kaydedilen bilgiler yeni faturalara aktarılır. Önceden oluşturulan faturaların saklanmış işletme bilgileri otomatik değiştirilmez.'],
            'links' => [['label' => 'İşletme bilgilerimi düzenle', 'route' => 'setting.index', 'params' => ['tab' => 'invoice_business'], 'permission' => 'manage company settings']],
        ],
        [
            'id' => 'logolar-tema', 'group' => 'baslangic', 'title' => 'Logolar, görünüm ve ortak standartlar',
            'intro' => 'Panel logosu, koyu tema logosu, sekme simgesi ve fatura logosu farklı alanlardır. İşletmenizin logosunu kullanım yerine göre seçebilirsiniz.',
            'steps' => ['Ayarlar → Kullanıcı profili bölümündeki İşletme logoları formunu açın.', 'Panel görsellerini PNG olarak yükleyin. Fatura logosu için PNG, JPG veya WebP seçebilirsiniz.', 'Fatura logosunda önerilen 600 × 240 piksel boyutunu kullanın. Ön izlemeyi kontrol edip Logoları kaydet düğmesine basın.', 'Üstteki ayarlar simgesinden renk ve tema seçeneklerini seçin.'],
            'notes' => ['Fatura logosu oranı korunarak 200 × 80 piksellik alana sığdırılır. Dosya sınırı 2 MB, fatura görseli için üst boyut sınırı 6000 × 6000 pikseldir.', 'Ayrı fatura logosu seçilmezse panel logosu kullanılır. Para birimi Türk lirası, saat dilimi İstanbul, saat biçimi 24 saattir. Platform adı esnaf tarafından değiştirilmez.'],
            'links' => [['label' => 'Profil ve logo ayarları', 'route' => 'setting.index', 'params' => ['tab' => 'user_profile_settings'], 'permission' => 'manage account settings']],
        ],
        [
            'id' => 'musteri-ekleme', 'group' => 'musteri', 'title' => 'Müşteri ekle mi, servisle müşteri ekle mi?',
            'intro' => 'Müşteri listesinde iki farklı kayıt yolu bulunur. Kullanacağınız yol, yalnızca kişiyi mi yoksa müşteriyle birlikte araç ve servisi de mi kaydedeceğinize bağlıdır.',
            'steps' => ['Sadece iletişim kaydı oluşturacaksanız Müşteri ekle seçeneğini kullanın.', 'Yeni gelen müşteri için aracı ve servisi de açacaksanız Servisle müşteri ekle seçeneğini kullanın; formun adımlarını sırayla tamamlayın.', 'Telefonu başında sıfır olmadan 10 hane girin. +90 ön ekini sistem ekler.', 'Müşterinin e-postası varsa kaydedin. Fatura bilgilendirmesi için doğru adresin girilmiş olması gerekir.', 'Kayıttan sonra müşteri listesinden inceleme veya düzenleme işlemini yapın. WhatsApp simgesiyle kayıtlı cep telefonu üzerinden sohbet açabilirsiniz.'],
            'notes' => ['WhatsApp simgesi geçerli Türkiye cep telefonu bulunan müşterilerde görünür. Simgeye tıklamak otomatik mesaj göndermez; sohbeti açar.', 'Aynı müşteriye ait birden fazla araç olabilir. İletişim bilgilerini değiştirirken doğru müşterinin kaydında olduğunuzu kontrol edin.'],
            'links' => [['label' => 'Müşteri listesi', 'route' => 'client.index', 'permission' => 'manage client']],
        ],
        [
            'id' => 'arac-kaydi', 'group' => 'musteri', 'title' => 'Araç kaydı ve müşteriye ulaşan takip bağlantısı',
            'intro' => 'Araç kaydı, müşteriyi aracına ve servislerine bağlar. Plaka, marka/model ve araçla ilgili ek bilgileri aynı kayıtta tutabilirsiniz.',
            'steps' => ['Araç listesinde yeni araç kaydını açın veya Servisle müşteri ekle adımını kullanın.', 'Araç sahibini, marka/modeli ve formdaki gerekli bilgileri seçin. Kilometre, sigorta ve not bilgilerini ihtiyacınıza göre tamamlayın.', 'Hazır QR etiketiniz varsa uygun etiketi seçin. Etiket yoksa QR alanını boş bırakabilirsiniz.', 'Kayıt sonrasında otomatik oluşan araç bağlantısını kullanın. Bu bağlantıyı daha sonra QR olarak da kullanabilirsiniz.'],
            'notes' => ['QR seçilmişse müşteriye o QR’ın bağlantısı, boş bırakılmışsa otomatik oluşturulan araç bağlantısı gönderilir. SMS ile gönderim merkezi SMS ayarlarına bağlıdır.', 'Müşteriye açık araç ekranı faturaları görüntülemek içindir; paneldeki servis yönetim ekranının tamamını müşteriye açmaz.'],
            'links' => [['label' => 'Araç listesi', 'route' => 'vehicle.index', 'permission' => 'manage vehicle']],
        ],
        [
            'id' => 'hazir-araclar', 'group' => 'musteri', 'title' => 'Hazır marka ve model listelerini yükleme',
            'intro' => 'Bilinen otomobil, motosiklet ve ağır vasıta markalarını tek tek yazmak yerine hazır listelerden yararlanabilirsiniz. Yükleme yalnızca kendi işletmenizde yapılır.',
            'steps' => ['Araç markaları ekranında Otomatik marka ve modeller oluştur seçeneğine basın.', 'Otomobil, motosiklet veya ağır vasıta listesini seçin. Yüklenecek marka ve model sayılarını kontrol edin.', 'Yükleme onayını işaretleyip Evet, yükle seçeneğine basın.', 'İşlem sonrasında markalar ve modeller ilgili listelerde görünür. Geri almak isterseniz ilgili listenin Geri al otomatik yüklemeyi düğmesini kullanın.'],
            'notes' => ['Mevcut kayıtlar korunur; aynı kayıt yeniden oluşturulmaz. Hazır listeler model yılı, motor ve donanım seçeneklerini kapsamaz.', 'Geri alma işlemi araçlarda kullanılan, düzenlenmiş veya başka bir hazır listede bulunan kayıtları korur. Bu nedenle her yüklenen kayıt mutlaka silinmeyebilir.'],
            'links' => [['label' => 'Araç markalarına git', 'route' => 'vehicle-type.index', 'permission' => 'manage vehicle type']],
        ],
        [
            'id' => 'qr-etiketleri', 'group' => 'musteri', 'title' => 'QR etiketleri: üretim, baskı ve araca tanımlama',
            'intro' => 'QR etiketlerini önceden üretip bastırabilir, araç geldiğinde kullanılabilir etiketi o araca tanımlayabilirsiniz.',
            'steps' => ['QR etiketleri bölümünden yeni etiketleri üretin ve PDF çıktısını alın.', 'Baskıyı tamamladıktan sonra bastırdığınızı belirten işlemi uygulayın; etiketler araca tanımlanabilir hâle gelir.', 'Henüz araca tanımlanmamış kullanılabilir etiketleri gerektiğinde yeniden PDF olarak yazdırın.', 'Araç kaydında uygun etiketi seçin ve müşterinin erişeceği bağlantıyı kontrol edin.'],
            'notes' => ['QR etiketi oluşturmak araç kaydı oluşturmak değildir. Etiket ile aracı ilişkilendirmek ayrı adımdır.', 'Araç bağlantısını, faturaları görüntüleme erişimi sağlayan özel bir bağlantı olarak paylaşın.'],
            'links' => [['label' => 'QR etiketlerine git', 'route' => 'vehicle-qr.index', 'permission' => 'create vehicle', 'owner_only' => true]],
        ],
        [
            'id' => 'arac-temizligi', 'group' => 'musteri', 'title' => 'İşlem görmeyen araçları temizleme',
            'intro' => 'Araç temizleme ekranı, belirli süredir işlem yapılmayan araçları inceleyip toplu olarak kaldırmanıza yardımcı olur.',
            'steps' => ['Araç listesindeki temizleme işlemini açın.', '3 ay, 6 ay veya 1 yıl gibi süre filtrelerini kullanın. Son işlem bilgisini ve toplam servis sayısını inceleyin.', 'Kaldırılacak araçları tek tek veya toplu seçin; onay vermeden önce listeyi kontrol edin.', 'Gerekirse silinenler görünümünden uygun kayıtları geri getirin.'],
            'notes' => ['Fatura, servis, ödeme ve stok kayıtları korunur. Araç ve ilgili müşterinin kaldırılması geçmiş faturaları silmek için kullanılmaz.', 'Temizleme kararı vermeden önce müşterinin başka aktif araçları ve kayıtları olup olmadığını dikkate alın.'],
            'links' => [['label' => 'Araç listesi', 'route' => 'vehicle.index', 'permission' => 'manage vehicle']],
        ],
        [
            'id' => 'randevu-kurulumu', 'group' => 'randevu', 'title' => 'Çalışma günleri ve saatlerini açma',
            'intro' => 'İşletmeye özel randevu bağlantınız değişmeyen bir kimlikle oluşturulur. Hangi gün ve saatlerde talep alacağınızı siz belirlersiniz.',
            'steps' => ['Randevular → Çalışma saatleri ve ayarlar bölümünü açın. Müşteriye görünen işletme adını yazın.', 'Haftalık tabloda açık olacak saatleri seçin. Her kutu bir saatlik aralığı temsil eder; yeşil kutular açıktır.', 'Müşterilerden randevu talebi al seçeneğini etkinleştirin.', 'İptal süresini ve cevapsız taleplerin kapanma süresini belirleyip ayarları kaydedin.', 'Müşteri sayfasını açarak uygun gün ve saatleri kontrol edin. Bağlantınızı işletmenizin web sitesi veya profilinde paylaşabilirsiniz.'],
            'notes' => ['Bir günde hiç saat seçilmemişse o gün kapalıdır. Saatler İstanbul saatine göredir.', 'Müşteriler en fazla bir hafta sonrasına randevu talep edebilir. Saatleri kapatmak mevcut randevuları otomatik iptal etmez.'],
            'links' => [['label' => 'Randevu ayarları', 'route' => 'appointments.settings', 'owner_only' => true]],
        ],
        [
            'id' => 'randevu-talepleri', 'group' => 'randevu', 'title' => 'Talebi inceleme, onaylama ve iptal takibi',
            'intro' => 'Müşteri uygun saati seçip talep oluşturur. Talep, işletmenin incelemesi ve onayı için panelinize gelir.',
            'steps' => ['Üstteki zil simgesinden yeni talebi açın veya Randevu talepleri listesine gidin.', 'Müşterinin bilgilerini, istediği zamanı ve talep detaylarını kontrol edin.', 'Uygun talebi panelden onaylayın; uygun olmayan talebi ilgili işlemle sonuçlandırın.', 'Müşteri iptal etmişse iptal bildirimini ve liste durumunu kontrol edin. İşletme planınızı buna göre güncelleyin.'],
            'notes' => ['SMS doğrulaması zorunluysa müşteri önce telefonuna gelen kodu girer. Süper admin zorunluluğu kaldırdığında talep SMS doğrulaması olmadan da oluşturulabilir.', 'Randevu onay SMS’i merkezi SMS yapılandırmasına bağlıdır. SMS iletimi ile paneldeki randevu durumunu ayrı kontrol edin.'],
            'links' => [['label' => 'Randevu talepleri', 'route' => 'appointments.index', 'owner_only' => true]],
        ],
        [
            'id' => 'genel-randevu', 'group' => 'randevu', 'title' => 'Genel servis aramasında işletmenizi gösterme',
            'intro' => 'Genel randevu sayfasında müşteri bölge, taşıt türü ve hizmet üzerinden işletme arar. Seçtiği işletmenin özel randevu sayfasına geçer.',
            'steps' => ['Randevu ayarlarındaki Genel randevu sayfasında işletmeniz bölümünü açın.', 'Genel servis aramasında görünme seçeneğini etkinleştirin ve ilinizi seçin. İstanbul için Avrupa veya Anadolu yakasını kullanın.', 'Otomobil, motosiklet ve ağır vasıta başlıklarında gerçekten verdiğiniz hizmetleri işaretleyin.', 'Müşteriye gösterilecek adresi girip kaydedin. Genel randevu sayfasından işletmenizin görünümünü kontrol edin.'],
            'notes' => ['Genel aramadaki hizmet seçimi ile servis kayıtlarında kullandığınız işçilik türleri farklı amaçlara hizmet eder.', 'Konum izni verilirse müşterinin bölgesi belirlenmesine yardımcı olunur; müşteri farklı bir il seçebilir. Puanlama sistemi bu rehberde mevcut bir özellik olarak sunulmaz.'],
            'links' => [['label' => 'Görünürlük ve hizmet ayarları', 'route' => 'appointments.settings', 'owner_only' => true], ['label' => 'Genel randevu sayfası', 'route' => 'directory.index']],
        ],
        [
            'id' => 'servis-turleri', 'group' => 'servis', 'title' => 'İşçilik türlerini ve çalışanları hazırlama',
            'intro' => 'Servis türü yapılan işin adını ve temel ücretini, çalışan seçimi ise işin kime atandığını belirler.',
            'steps' => ['Personel listesinde servisi atayacağınız çalışanı kaydedin.', 'Servis türleri bölümünde yağ değişimi, fren bakımı gibi işleriniz için kayıt oluşturun ve standart tutarını girin.', 'Vergi ayarlarında kullanacağınız seçenekleri kontrol edin. Hazır vergi seçenekleri eksikse ürün rehberinden ekleyebilirsiniz.', 'Servis formunda türü seçtiğinizde gelen tutarı kontrol edin; işin kapsamına göre düzenleyin.'],
            'notes' => ['Çalışan seçimi servis formunda gereklidir. Çalışan yetkilerini işi için gereken alanlarla sınırlandırın.', 'İşletmenizin hizmetlerine göre kendi servis türlerinizi oluşturun; genel randevu hizmetlerinin seçilmiş olması bu kayıtları otomatik oluşturmaz.'],
            'links' => [['label' => 'Servis türleri', 'route' => 'service-type.index', 'permission' => 'manage service type'], ['label' => 'Personel listesi', 'route' => 'employee.index', 'permission' => 'manage employee']],
        ],
        [
            'id' => 'servis-olusturma', 'group' => 'servis', 'title' => 'Yeni servis kaydı ve harici işçilik',
            'intro' => 'Servis formu müşteri, araç, çalışan ve yapılacak işlemleri aynı kayıtta toplar. Kaydettiğinizde işlemlere ait fatura da oluşturulur.',
            'steps' => ['Yeni servis oluştur seçeneğini açın. Müşteriyi seçip o müşterinin aracını belirleyin.', 'Çalışanı ve servis durumunu seçin. Başlangıç/bitiş tarihleri ve saatlerini biliyorsanız girin; boş bırakabilirsiniz.', 'İşlem satırlarında servis türünü, işçilik tutarını, vergisini ve açıklamasını girin. Birden fazla işi ayrı satırlarla ekleyin.', 'Ek ücret için Harici işçilik tutarını ve buna uygulanacak vergiyi seçin.', 'Kaydedin; oluşan faturadaki işçilik, vergi ve toplam tutarı kontrol edin.'],
            'notes' => ['Harici işçilik, müşteriye faturalanan ek işçilik ücretidir; başka bir ustaya ödediğiniz gideri kaydetme alanı değildir.', 'Kullanılan stok ürünlerini ilgili faturaya ekleyin. Randevu kaydı oluşturmak veya onaylamak bu servis formunun yerine geçmez.'],
            'links' => [['label' => 'Servis oluştur', 'route' => 'service.create', 'permission' => 'create service'], ['label' => 'Adım adım servis rehberi', 'route' => 'service.setup', 'permission' => 'manage service', 'owner_only' => true]],
        ],
        [
            'id' => 'servis-takibi', 'group' => 'servis', 'title' => 'Servis listesi, pano ve takvim',
            'intro' => 'Günlük servisleri işin durumuna göre takip edin. Liste, pano ve takvim aynı iş akışını farklı görünümlerle sunar.',
            'steps' => ['Servis listesinde müşteriyi, aracı ve kaydın durumunu inceleyin.', 'İş başladığında, parça beklendiğinde veya tamamlandığında servis durumunu güncelleyin.', 'Bugünkü servisler görünümünü günlük planlama için kullanın.', 'Servis panosunda durumlara göre işleri takip edin; takvimde tarihli kayıtları inceleyin.'],
            'notes' => ['Parça bekleniyor veya tamamlandı gibi durumlar işin aşamasını anlatır. Müşteriden alınan parayı faturadaki ödeme işlemiyle kaydedin.', 'Tarih girilmemiş servisleri takip etmek için liste ve pano görünümlerini kullanın.'],
            'links' => [['label' => 'Servis listesi', 'route' => 'service.index', 'permission' => 'manage service'], ['label' => 'Servis panosu', 'route' => 'service.kanban', 'permission' => 'kanban service']],
        ],
        [
            'id' => 'fatura-icerigi', 'group' => 'fatura', 'title' => 'Fatura oluşturma ve müşteri bilgileri',
            'intro' => 'Fatura; hizmet, ürün, ek işçilik, vergi ve indirimleri bir araya getirir. Sistemdeki belge temsili faturadır; resmî e-Fatura/e-Arşiv yerine geçmez.',
            'steps' => ['Fatura oluştururken müşteri ve ilgili servisi seçin. Servisten oluşan fatura varsa mevcut faturayı kullanın.', 'Müşterinin kayıtlı adı, telefonu, e-postası ve kullanılabilir adres bilgilerini kontrol edin.', 'Müşteri bilgileri ekle/doldur alanından eksik adres veya vergi bilgilerini isteğe bağlı tamamlayın.', 'Hizmet ve ürün satırlarını, miktarları ve vergileri kontrol edip faturayı kaydedin.'],
            'notes' => ['Müşteriyi seçmek ile faturaya ek müşteri bilgileri yazmak farklı adımlardır. Ek alanlar zorunlu tutulmaz.', 'Satıcı bilgileri kendi işletme ayarlarınızdan gelir. Aynı iş için yanlışlıkla ikinci fatura oluşturmamaya dikkat edin.'],
            'links' => [['label' => 'Fatura listesi', 'route' => 'invoice.index', 'permission' => 'manage invoice']],
        ],
        [
            'id' => 'indirim-odeme', 'group' => 'fatura', 'title' => 'İndirim, kısmi ödeme ve kalan bakiye',
            'intro' => 'İndirim faturanın toplamını değiştirir; ödeme ise müşteriden tahsil edilen tutarı kaydeder. Kalan bakiye bunların sonucunda oluşur.',
            'steps' => ['Faturadaki ürün, hizmet ve vergi tutarlarını kontrol edin.', 'İndirim uygulayacaksanız fatura indirim alanını kullanın; toplamın ve indirim satırının doğru göründüğünü kontrol edin.', 'Ödeme ekle işlemiyle gerçekte tahsil ettiğiniz tutarı ve ödeme bilgilerini kaydedin.', 'Kısmi ödemelerde kalan bakiyeyi takip edin; her tahsilatı ayrı kayıtla ekleyin.'],
            'notes' => ['İndirim uygulamak ödeme kaydı değildir. Para henüz alınmadıysa tahsilat yapılmış gibi kaydetmeyin.', 'Ödeme yapmak stok miktarını değiştirmez. Stok ürün faturaya eklendiği anda düşer.'],
            'links' => [['label' => 'Faturalar ve ödemeler', 'route' => 'invoice.index', 'permission' => 'manage invoice']],
        ],
        [
            'id' => 'fatura-paylasma', 'group' => 'fatura', 'title' => 'Yazdırma, araç bağlantısı ve e-posta',
            'intro' => 'Fatura listesindeki yazdırma ve ödeme simgeleri işlemleri hızlandırır. Müşteri kendi araç bağlantısından faturalarını görüntüleyebilir.',
            'steps' => ['Fatura listesindeki inceleme simgesiyle içeriği açın. Yazdır simgesinden baskı görünümünü kontrol edin.', 'Logo, satıcı bilgileri, müşteri bilgileri, indirim ve temsili fatura dipnotunu inceleyin.', 'Müşterinin e-postasını doğru kaydedin. Fatura bilgilendirme mesajları platformun e-posta yapılandırmasına göre gönderilir.', 'Araç bağlantısını müşteriye ulaştırın. Müşteri bu bağlantı veya QR üzerinden faturalarına erişir.'],
            'notes' => ['SMS ve e-posta gönderimi merkezi servislerin etkin ve doğru yapılandırılmış olmasına bağlıdır. Belge oluşturulmuş olması mesajın mutlaka teslim edildiği anlamına gelmez.', 'Fatura e-postası şablonlarını platform yöneticisi düzenler; faturalar müşteriye sanayirandevu.com adına bildirilir.'],
            'links' => [['label' => 'Fatura listesine git', 'route' => 'invoice.index', 'permission' => 'manage invoice']],
        ],
        [
            'id' => 'urun-kurulumu', 'group' => 'stok', 'title' => 'Vergi → birim → kategori → ürün',
            'intro' => 'Ürün kaydından önce kullanacağınız vergileri ve birimleri hazırlayın. Kategori ürünleri gruplandırır; kategorisiz kayıt da mümkündür.',
            'steps' => ['Vergi seçeneklerini kontrol edin. Sistemde hazır KDV %20, %10 ve %1 seçenekleri bulunur; ürününüze uygun seçeneği kullanın.', 'Ürün birimini belirleyin. Adet, litre, mililitre, kilogram, gram, metre, santimetre, takım, çift, paket, kutu ve bidon hazır seçeneklerdir.', 'İsterseniz yağ, filtre veya fren parçaları gibi kategoriler oluşturun.', 'Ürün adı, ürün kodu, stok miktarı, alış/satış fiyatı, alış tarihi ve vergi bilgilerini girip kaydedin.'],
            'notes' => ['Hazır vergi ve birimler yeni işletmelerde oluşturulur. Eksikse ürün rehberindeki yükleme düğmesiyle tamamlayın; mevcut kayıtlar değiştirilmez.', 'Kategori isteğe bağlıdır. Birim seçimi gereklidir; miktarı seçtiğiniz birime göre anlamlı girin.'],
            'links' => [['label' => 'Ürün ve stok rehberi', 'route' => 'inventory.setup', 'permission' => 'manage item', 'owner_only' => true], ['label' => 'Ürün listesi', 'route' => 'item.index', 'permission' => 'manage item']],
        ],
        [
            'id' => 'stok-mantigi', 'group' => 'stok', 'title' => 'Stok ne zaman düşer, ne zaman geri gelir?',
            'intro' => 'Stok hareketleri ödeme durumundan bağımsızdır. Bir ürün faturaya eklendiğinde kullanılan miktar hemen stoktan düşer.',
            'steps' => ['Ürün kaydında mevcut stok miktarını girin. Miktar artışı ürün alımı olarak hesaplara yansıyabilir; aynı alımı ayrıca gider yazmadan önce kontrol edin.', 'Faturaya ürün eklerken kullanılacak miktarı girin. Yetersiz stok varsa işlemi tamamlamadan önce stok miktarını kontrol edin.', 'Faturadaki ürün miktarını değiştirirken stokta oluşan farkı kontrol edin. Satırı kaldırdığınızda kullanılan miktar geri eklenir.', 'Fatura silerken ürünlerin stoklara geri eklenip eklenmeyeceğini soran seçimi gerçek duruma göre cevaplayın.'],
            'notes' => ['Ödenmedi diye ürün stokta kalmaz; ödendi diye tekrar stoktan düşmez.', 'Fiziksel olarak kullanılan ürünü, yalnızca fatura silindiği için geri dönmüş kabul etmeyin. Silme onayındaki stok tercihini dikkatle seçin.'],
            'links' => [['label' => 'Stok listesi', 'route' => 'item.index', 'permission' => 'manage item']],
        ],
        [
            'id' => 'elden-satis', 'group' => 'stok', 'title' => 'Servis açmadan elden ürün satışı',
            'intro' => 'Elden satış, araç veya servis kaydı açmadan harici ürün satışlarını stok ve mali hesaplara dâhil etmek içindir.',
            'steps' => ['Ürün listesindeki Elden satış işlemini açın.', 'Satılacak adedi ve satış birim fiyatını kontrol edin.', 'Satışı onaylayın; stok azalır ve satış kaydı oluşur.', 'Kâr-zarar raporunda elden satışın ilgili tarih aralığına yansımasını inceleyin.'],
            'notes' => ['Miktarı satıştan önce kontrol edin. Aynı satışı ikinci kez kaydetmeyin.', 'Elden satış kaydıyla rapora alınan tutarı ayrıca manuel gelir olarak yeniden yazmak hesabı tekrarlayabilir.'],
            'links' => [['label' => 'Ürünlerden satış yap', 'route' => 'item.index', 'permission' => 'manage item']],
        ],
        [
            'id' => 'finans-rapor', 'group' => 'stok', 'title' => 'Gelir, gider ve kâr-zarar raporları',
            'intro' => 'Raporlar girdiğiniz mali kayıtlara dayanır. Fatura toplamı, tahsil edilen ödeme ve ürün alış gideri farklı değerlerdir.',
            'steps' => ['Müşteriden aldığınız ödemeleri ilgili faturaya kaydedin.', 'Kira veya işletme harcaması gibi giderleri Gider kayıtları bölümüne girin.', 'Ürün alımlarından otomatik oluşan giderleri kontrol edin; aynı alımı ayrıca tekrar gider kaydetmeyin.', 'Gelir, gider ve kâr-zarar raporlarında tarih aralığını seçin. Beklediğiniz kayıtların seçilen aralıkta olduğundan emin olun.'],
            'notes' => ['Kesilmiş fakat tahsil edilmemiş faturayı alınmış para gibi yorumlamayın. Alacak takibi için faturanın kalan bakiyesine bakın.', 'Bu raporlar işletme takibi içindir; resmî muhasebe beyannamesi veya resmî fatura entegrasyonu anlamına gelmez.'],
            'links' => [['label' => 'Kâr-zarar raporu', 'route' => 'report.profit_loss', 'permission' => 'manage profile and loss report'], ['label' => 'Gider kayıtları', 'route' => 'expense.index', 'permission' => 'manage expense']],
        ],
        [
            'id' => 'teklif-notlar', 'group' => 'servis', 'title' => 'Teklifler, notlar ve iletişim rehberi',
            'intro' => 'Henüz kesinleşmemiş işler için teklif, günlük hatırlatmalar için not panosu, işletme bağlantılarınız için iletişim rehberi kullanabilirsiniz.',
            'steps' => ['Teklifler bölümünde müşteri için hizmet ve ürün bilgilerini hazırlayın; tutarları kontrol edin.', 'Müşteriyle karar vermeden önce teklifin kapsamını netleştirin.', 'İş kesinleştiğinde servis, fatura ve tahsilatı ilgili ekranlardan takip edin.', 'Günlük iş notlarını not panosuna, tedarikçi ve diğer bağlantıları iletişim rehberine kaydedin.'],
            'notes' => ['Teklif, müşteriden para tahsil edildiği anlamına gelmez. Tahsilatın ayrı kaydını oluşturun.', 'Not panosu servis durumu veya ödeme kaydının yerine geçmez.'],
            'links' => [['label' => 'Teklifler', 'route' => 'quotation.index', 'permission' => 'manage quotation'], ['label' => 'Not panosu', 'route' => 'note.index', 'permission' => 'manage note'], ['label' => 'İletişim rehberi', 'route' => 'contact.index', 'permission' => 'manage contact']],
        ],
        [
            'id' => 'roller-guvenlik', 'group' => 'hesap', 'title' => 'Yetkiler, şifre ve iki aşamalı doğrulama',
            'intro' => 'Çalışanların erişebildiği bölümler rol ve yetkilere bağlıdır. İki aşamalı doğrulama, giriş sırasında şifrenize ek doğrulama kodu ister.',
            'steps' => ['Roller ve yetkiler bölümünden çalışanların erişimlerini görevlerine göre düzenleyin.', 'Ayarlar → Şifre bölümünden hesabınızın şifresini değiştirebilirsiniz. Şifre unutulursa giriş ekranındaki sıfırlama bağlantısını kullanın.', 'İki aşamalı doğrulamayı kurarken QR’ı Google Authenticator veya uyumlu bir doğrulama uygulamasıyla tarayın.', 'Uygulamanın ürettiği kodu girip kurulumu onaylayın. Gösterilen kurtarma kodlarını güvenli bir yerde saklayın.', 'Telefon değişikliği veya giriş sorunu yaşarsanız platform desteğine başvurun.'],
            'notes' => ['Kurtarma kodları tek kullanımlıktır. QR ve kurtarma kodlarını destek bileti veya mesajla paylaşmayın.', 'Süper admin gerekli durumda doğrulamayı kapatabilir veya yeniden kurulum isteyebilir. Yeniden kurulum sonrası eski kodlar kullanılamaz.'],
            'links' => [['label' => 'Hesap ayarları', 'route' => 'setting.index', 'permission' => 'manage account settings'], ['label' => 'Roller ve yetkiler', 'route' => 'role.index', 'permission' => 'manage role']],
        ],
        [
            'id' => 'paket-kapasite', 'group' => 'hesap', 'title' => 'Paketim, araç limiti ve ek kapasite',
            'intro' => 'Araç limiti aylık eklenen araç sayısı değil, işletmenizin sistemde kayıtlı toplam araç sayısı üzerinden değerlendirilir.',
            'steps' => ['Paketim ve abonelik bölümünde aktif paketinizi ve süresini kontrol edin.', 'Demo için 50; standart paketler için 500, 1000, 2000 veya 3000 araç kapasitesini inceleyin.', '3000 araç sonrasında gerekirse 500 araçlık ek kapasite talebini oluşturun ve sunulan ücret/koşulları kontrol edin.', 'Ek kapasiteyi kabul edip ilgili abonelik işlemlerini tamamlayın.'],
            'notes' => ['Paket ücretlerini ve hangi paketlerin kullanılabildiğini platform yöneticisi belirler. Ek kapasite kendiliğinden satın alınmaz.', 'Abonelik erişimi veya kapasiteyle ilgili bir sorun yaşarsanız destek bileti açın.'],
            'links' => [['label' => 'Paket bilgilerim', 'route' => 'subscriptions.index', 'permission' => 'manage pricing packages'], ['label' => 'Ek kapasite', 'route' => 'capacity.index', 'owner_only' => true]],
        ],
        [
            'id' => 'bildirim-destek', 'group' => 'hesap', 'title' => 'Bildirimler, kurulum uyarıları ve destek bileti',
            'intro' => 'Zil ve uyarı simgesi farklı amaçlar taşır. Zil gelen olayları, uyarı kutusu eksik kurulumları gösterir. Bilgi simgesi bu eğitim rehberini açar.',
            'steps' => ['Zil simgesinden randevu taleplerini ve destek yanıtlarını takip edin. Bildirime tıklayarak ilgili kayda gidin.', 'Uyarı kutusunda eksik işletme bilgileri, fatura logosu, hazır listeler ve ilk ürün/servis adımları için yönlendirmeleri kullanın.', 'Destek biletleri bölümünden konu, öncelik ve açıklama girerek yeni bilet açın.', 'Destekten gelen yanıta aynı bilet üzerinden cevap verin. Çözülen bileti kapatın; gerektiğinde yeniden açın.'],
            'notes' => ['Bildirim kutusu açık ve görünür sayfada 10 saniyede bir yenilenir. Destek bileti açıldığında ilgili destek bildirimi okunmuş sayılır.', 'Sorunu anlatırken hangi ekran ve işlemde olduğunu belirtin. Şifre, SMS doğrulama kodu veya iki aşamalı doğrulama anahtarı göndermeyin.'],
            'links' => [['label' => 'Destek biletleri', 'route' => 'support.index']],
        ],
    ],
];
